url=https://accounts.google.com/signin/v2/identifier?service=mail
email=devopstest789@gmail.com
password=Testing@2000
browser=chrome
timeout=10
urlSauceLab=https://www.saucedemo.com/?utm_source=copilot.com
usernameSauceLab=standard_user
passwordSauceLab=secret_sauce
url6=https://www.saucedemo.com
username2=standard_user
password143=secret_sauce